name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.101'
        
    - name: Restore dependencies
      run: dotnet restore TradingView.Screener.sln
      
    - name: Build
      run: dotnet build TradingView.Screener.sln --configuration Release
      
    - name: Test
      run: dotnet test TradingView.Screener.sln --configuration Release
      
    - name: Pack
      run: |
        mkdir -p nupkg
        dotnet pack src/TradingView.Screener/TradingView.Screener.csproj --configuration Release --output nupkg
        dotnet pack src/TradingView.Screener.Cli/TradingView.Screener.Cli.csproj --configuration Release --output nupkg
    
    - name: Upload NuGet packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: nupkg/*.nupkg 